name: CI

on: [push]

jobs:
  build:

    runs-on: linux

    steps:
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./*
          remote: /srv/http/megsoraxyz/
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }} 
